services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UNAME=${UNAME}
        - UID=${UID}
        - GID=${GID}
    user: "${UID}:${GID}"
    volumes:
      - .:/usr/src/phpc
